### ISSUE TITLE
不应该用0来作为认证成功的标识

### ISSUE THREAD

**Issue by shenhao815** [huaweicloud/huaweicloud-iot-device-sdk-java#43]
在MqttConnection.java的connect方法中，如果认证失败时返回connectResultCode，而在出现一些异常时，connectResultCode的值也是0。
![image](https://user-images.githubusercontent.com/30065097/131425687-1347c65b-2ca0-41c1-ad26-a092cb916e9b.png)
![image](https://user-images.githubusercontent.com/30065097/131425872-c863ce5b-c850-4b6a-8de3-63b35a4b8149.png)
![image](https://user-images.githubusercontent.com/30065097/131425873-4577f249-ce70-4b84-b4f1-8332ff052ccc.png)

**Comment by louiscrazy** [comment]
Solved.

**Comment by louiscrazy** [comment]
#89
